export const CREATE_NOTE = "http://localhost:5000/api/v1/notes/create"
export const ALL_NOTES = "http://localhost:5000/api/v1/notes"
export const UPDATE_NOTE = "http://localhost:5000/api/v1/notes/update"
export const DELETE_NOTE = "http://localhost:5000/api/v1/notes/delete"
export const NOTE = "http://localhost:5000/api/v1/notes"